import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X,Sun,Moon,EyeOff,Eye,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';

import DICT_DATA from './dict.json';
const DICT = DICT_DATA as Record<string, string>;

const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,hidden:[]};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const getDeviceType=()=>{if(typeof navigator==='undefined')return'pc';const ua=navigator.userAgent;if(/iPad|iPhone|iPod/.test(ua))return'ios';if(/android/i.test(ua))return'android';return'pc';};
 const [deferredPrompt, setDeferredPrompt] = useState<any>(null), [showInstallBanner, setShowInstallBanner] = useState(false), [showInstallFallback, setShowInstallFallback] = useState(false);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(()=>{if(typeof window!=='undefined'){const saved=localStorage.getItem('atlas_visible_systems');if(saved){try{return{...initial,visible:JSON.parse(saved)};}catch(e){}}if((window as any).Capacitor)return{...initial,visible:SYSTEMS.map(s=>s.id).filter(id=>id!=='integumentary')};}return initial;}),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(typeof window!=='undefined'&&window.innerWidth>=768?'layers':null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[lang,setLang]=useState<'en'|'zh'>(typeof navigator !== 'undefined' && navigator.language.startsWith('zh') ? 'zh' : 'en');
 const [theme, setTheme] = useState<'light'|'dark'>(() => {
    if (typeof window !== 'undefined') {
        const saved = localStorage.getItem('atlas_theme');
        if (saved === 'dark' || saved === 'light') return saved;
        return 'dark';
    }
    return 'dark';
});

useEffect(() => {
    if (typeof window !== 'undefined') {
        localStorage.setItem('atlas_theme', theme);
    }
}, [theme]);
 useEffect(()=>{if(theme==='dark')document.documentElement.classList.add('dark');else document.documentElement.classList.remove('dark');},[theme]);
 useEffect(()=>{localStorage.setItem('atlas_visible_systems',JSON.stringify(state.visible));},[state.visible]);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);
  const isChina = new Date().getTimezoneOffset() === -480;
  const isCapacitor = typeof window !== 'undefined' && !!(window as any).Capacitor;
  const ossBaseUrl = 'https://cdn.jsdelivr.net/gh/undergravity/human-atlas@main/public';
  const basePath = (isChina && !isCapacitor) ? ossBaseUrl : import.meta.env.BASE_URL.replace(/\/$/, '');
  const atlasUrl = basePath + '/models/atlas.json';
  fetch(atlasUrl,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{const atl=data as Atlas;atl.concepts.forEach(c=>{if(DICT[c.name.toLowerCase()])c.nameZh=DICT[c.name.toLowerCase()]});atl.parts.forEach(p=>{if(DICT[p.name.toLowerCase()])p.nameZh=DICT[p.name.toLowerCase()]});setAtlas(atl);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)||(c.nameZh&&c.nameZh.includes(term))).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false,focus:(s.focus||0)+1}));setDetails(true);if(typeof window!=='undefined'&&window.innerWidth<768)setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 useEffect(()=>{const h=(e:any)=>{e.preventDefault();setDeferredPrompt(e);if(typeof window!=='undefined'&&window.innerWidth<768){if(!localStorage.getItem('pwa_prompted')){setShowInstallBanner(true);localStorage.setItem('pwa_prompted','true');}}};window.addEventListener('beforeinstallprompt',h);return ()=>window.removeEventListener('beforeinstallprompt',h);},[]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,nameZh:p.nameZh,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);if(typeof window!=='undefined'&&window.innerWidth<768)setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter((x:SystemId)=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:typeof window!=='undefined'&&!!(window as any).Capacitor?SYSTEMS.map(sys=>sys.id):DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);if(typeof window!=='undefined'&&window.innerWidth<768)setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const handleInstall = () => {
   if (getDeviceType() === 'android') {
     const link = document.createElement('a');
     link.href = 'https://pub-a1ad7ac347d14bcd8412ac216833d9f9.r2.dev/HumanAtlas.apk';
     link.download = 'HumanAtlas.apk';
     document.body.appendChild(link);
     link.click();
     document.body.removeChild(link);
     setShowInstallBanner(false);
     return;
   }
   setShowInstallBanner(false);
   if(deferredPrompt){
     deferredPrompt.prompt();
     deferredPrompt.userChoice.then((r:any)=>{
       if(r.outcome==='accepted')setDeferredPrompt(null);
     });
   }else{
     setShowInstallFallback(true);
   }
 };
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} theme={theme} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onClear={()=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false}));}} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {lang==='zh'?'交互式解剖':'INTERACTIVE ANATOMY'}</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} {lang==='zh'?'个建模部分':'modeled pieces'} <span>·</span> BodyParts3D</div></header>
  {panel && <div className="panel-overlay mobile-only" onClick={() => setPanel(null)} />}
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={`icon-button ${panel==='layers'?'active':''}`} onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={18}/></Button><Button variant="ghost" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')} className="icon-button" aria-label="Toggle theme">{theme==='dark'?<Sun size={18}/>:<Moon size={18}/* eslint-disable-line react/jsx-no-undef */ />}</Button><Button variant="ghost" onClick={()=>setLang(l=>l==='en'?'zh':'en')} className="icon-button lang-toggle" aria-label="Toggle language"><span>{lang==='en'?'中':'EN'}</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>{lang==='zh'?'查找部位':'Find a structure'}</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="Install App" onClick={handleInstall}><Download size={18}/></Button><Button variant="ghost" className="icon-button mobile-only" aria-label="Assemble and reset" onClick={reset}><RotateCcw size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'is-open mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>{lang==='zh'?'系统':'Systems'}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{lang==='zh'?'全部':'All'}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{lang==='zh'?'骨骼':'Skeleton'}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{lang==='zh'?'器官':'Organs'}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={lang==='zh'?`仅显示 ${s.nameZh||s.name}`:`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{lang==='zh'?(s.nameZh||s.name):s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={lang==='zh'?`显示 ${s.nameZh||s.name}`:`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span>{state.hidden&&state.hidden.length>0&&<Button variant="ghost" onClick={()=>setState(s=>({...s,hidden:[]}))}>{lang==='zh'?'恢复隐藏':'Restore'}</Button>}<Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{lang==='zh'?'隐藏全部':'Hide all'}</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>{lang==='zh'?'查找部位':'Find a structure'}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>lang==='zh'?(c.nameZh||c.name):c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={lang==='zh'?'心脏, 股骨, 颅神经…':'Heart, femur, cranial nerve…'} aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{lang==='zh'?'没有找到匹配的部位。':'No structures match your search.'}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{lang==='zh'?(c.nameZh||c.name):c.name}</span><span className="small-number">{c.elements.length} {lang==='zh'?'块':(c.elements.length===1?'piece':'pieces')}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?((lang==='zh'?(chosen?.nameZh||chosen?.name):chosen?.name)??(lang==='zh'?'选中的结构':'SELECTED STRUCTURE')):state.explode>.95?(lang==='zh'?'解剖清单':'ANATOMICAL INVENTORY'):state.explode>.05?(lang==='zh'?'分离的结构':'SEPARATED STRUCTURES'):(lang==='zh'?'成年人类 · 男性':'ADULT HUMAN · MALE')}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><div className="explode-control"><div className="explode-label"><label id="explode-label">{lang==='zh'?'展开解剖':'Explode anatomy'}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{lang==='zh'?'组合':'Assembled'}</span><span>{lang==='zh'?'拆分':'Every piece'}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>{lang==='zh'?'重置':'Reset'}</span></Button></div>
  <footer className="studio-footer"><span className="desktop-only">{state.explode>.8?(lang==='zh'?'拖动平移':'Drag to pan'):(lang==='zh'?'拖动旋转':'Drag to orbit')} <b>·</b> {lang==='zh'?'捏合缩放':'Pinch to zoom'} <b>·</b> {lang==='zh'?'点击查看':'Tap to inspect'}</span><span className="mobile-only">{lang==='zh'?'双指拖动/缩放，左右滑动旋转，点击查看':'Drag/pinch to zoom/pan, swipe to rotate, tap to inspect'}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{lang==='zh'?'来源与致谢':'Source & credits'} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{lang==='zh'?'准备解剖结构':'Preparing the anatomy'}</strong><span>{progress}% · {lang==='zh'?'加载中':'Loading'} {atlas?.parts.length.toLocaleString()??'2,234'} {lang==='zh'?'块':'pieces'}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?(lang==='zh'?(system.nameZh||system.name):system.name):(lang==='zh'?'解剖学':'ANATOMY')}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{lang==='zh'?(chosen?.nameZh||chosen?.name):chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system,lang):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">{lang==='zh'?'系统概览 · 源于真实解剖模型':'System overview · structure identified from source anatomy'}</span>}<div className="structure-meta"><span>{lang==='zh'?'图谱编号':'Atlas reference'}<strong>{chosen?.id}</strong></span><span>{lang==='zh'?'选中块数':'Selected pieces'}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{lang==='zh'?'包含的结构':'Included structures'}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{lang==='zh'?(parts.get(p.id)?.nameZh||p.name):p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{lang==='zh'?`还有 ${selectedParts.length-50} 块模型`:`And ${selectedParts.length-50} more modeled pieces.`}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{lang==='zh'?'查看原始数据':'View anatomical source'} <ArrowUpRight size={14}/></a></div><div className="detail-actions">{(()=>{const isHidden=state.selected.some(id=>(state.hidden||[]).includes(id));return <Button className="primary-action" onClick={()=>{setState(s=>{const h=s.selected.some(id=>(s.hidden||[]).includes(id));return h?{...s,hidden:(s.hidden||[]).filter(id=>!s.selected.includes(id))}:{...s,hidden:[...(s.hidden||[]),...s.selected]};});}}>{isHidden?<Eye size={18}/>:<EyeOff size={18}/>}{isHidden?(lang==='zh'?'显示该结构':'Show structure'):(lang==='zh'?'隐藏该结构':'Hide structure')}<ChevronRight size={16}/></Button>})()}<Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?(lang==='zh'?'显示周围结构':'Show surrounding anatomy'):(lang==='zh'?'隔离结构':'Isolate structure')}<ChevronRight size={16}/></Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{lang==='zh'?'来源与范畴':'SOURCE & SCOPE'}</div><SheetTitle className="structure-title">{lang==='zh'?'人体，一览无余。':'A body, revealed.'}</SheetTitle><SheetDescription>{lang==='zh'?'探索来自 BodyParts3D 的成年男性参考解剖图谱。':'Explore the adult male reference anatomy from BodyParts3D.'}</SheetDescription><div className="about-copy"><p><strong>{lang==='zh'?'男性 · BodyParts3D':'Male · BodyParts3D'}</strong><br/>{lang==='zh'?'2,234个独立网格和3,432个命名概念，来自成年男性参考解剖结构。':'2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.'}</p><p>{lang==='zh'?'该参考不包含所有人体结构或变异。命名的概念可以包含多个部分；每个源网格仅渲染一次。':'This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.'}</p><p>{lang==='zh'?'颜色和系统分组专为探索设计。几何图形已针对Web端进行了简化，简短解释提供一般教育背景。这是解剖学参考，并非诊断或手术工具。':'Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.'}</p><h3>{lang==='zh'?'来源':'Source'}</h3><p>{lang==='zh'?'BodyParts3D, © 生命科学数据库中心，基于CC Attribution 4.0 International许可。':'BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.'}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{lang==='zh'?'数据集许可':'Dataset license'} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{lang==='zh'?'原始几何模型和元数据':'Original geometry & metadata'} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{lang==='zh'?'阅读源出版物':'Read the source publication'} <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
  {showInstallBanner && <div className="install-banner glass"><div className="install-banner-content"><Download size={22} style={{color:'#458a85'}}/><div><strong>{lang==='zh'?'保存至设备':'Install App'}</strong><p>{lang==='zh'?'添加到主屏幕以全屏体验':'Add to home screen for full-screen experience'}</p></div></div><div className="install-banner-actions"><Button onClick={handleInstall}>{lang==='zh'?'安装':'Install'}</Button><Button variant="ghost" onClick={()=>setShowInstallBanner(false)} aria-label="Close"><X size={18}/></Button></div></div>}
  {showInstallFallback && <div className="panel-overlay" onClick={()=>setShowInstallFallback(false)} style={{zIndex:60,display:'flex',alignItems:'center',justifyContent:'center'}}><div className="install-fallback glass" onClick={e=>e.stopPropagation()}><div className="panel-heading"><span>{lang==='zh'?'安装提示':'Installation Guide'}</span><Button variant="ghost" className="icon-button" onClick={()=>setShowInstallFallback(false)}><X size={18}/></Button></div><div className="install-fallback-body"><p>{lang==='zh'?'请按照以下步骤保存应用以获得全屏体验：':'Please follow these steps to install the app for a full-screen experience:'}</p><ol>{getDeviceType()==='ios'?<><li>{lang==='zh'?'点击浏览器底部的「分享」图标':'Tap the Share icon at the bottom of Safari'}</li><li>{lang==='zh'?'向下滑动，选择「添加到主屏幕」':'Scroll down and select "Add to Home Screen"'}</li></>:getDeviceType()==='android'?<><li>{lang==='zh'?'点击浏览器右上角的「菜单」图标 (⋮)':'Tap the Menu icon (⋮) in your browser'}</li><li>{lang==='zh'?'选择「添加到主屏幕」或「安装应用」':'Select "Add to Home Screen" or "Install App"'}</li></>:<><li>{lang==='zh'?'点击浏览器地址栏右侧的「安装」图标':'Click the Install icon on the right side of the address bar'}</li><li>{lang==='zh'?'或在浏览器菜单中选择「安装应用」':'Or select "Install App" from the browser menu'}</li></>}</ol><Button className="primary-action" style={{marginTop:'20px',justifyContent:'center',width:'100%'}} onClick={()=>setShowInstallFallback(false)}>{lang==='zh'?'我知道了':'Got it'}</Button></div></div></div>}
 </main>;
}
